# Generated by Django 3.2.3 on 2021-06-19 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("birth_date", models.DateField(null=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "patient",
            },
        ),
        migrations.CreateModel(
            name="StudyModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("urgency_level", models.CharField(max_length=4)),
                ("body_part", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studies",
                        related_query_name="study",
                        to="api.patientmodel",
                    ),
                ),
            ],
            options={
                "db_table": "study",
            },
        ),
    ]
