name: Build, Lint and Test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            max-parallel: 4
            matrix:
                db: [mysql]
                python-version: [3.8]
                include:
                    - db: mysql

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
                  architecture: x64
            - name: Start MySQL
              run: |
                  sudo systemctl start mysql.service
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip pipenv
                  pipenv lock -r --dev > requirements.txt
                  python -m pip install --no-cache-dir -r requirements.txt
            - name: Check Lint
              run: |
                  black --check .
            - name: Run Tests
              env:
                  SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  DB_NAME: BACK_CHALLENGE
                  DB_USER: root
                  DB_PASS: root
                  DB_HOST: 127.0.0.1
                  DB_PORT: 3306
              run: python manage.py test api/tests
